steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access 1 --secret="dbt_service_account" --format="json" > /secret/dbt_service_account.json

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'auth'
      - 'activate-service-account'
      - 'dbt-service-account@bigquerysheets-404104.iam.gserviceaccount.com'
      - '--key-file=/secret/dbt_service_account.json'

#  - name: "gcr.io/cloud-builders/docker"
#    args:
#      - "build"
#      - "-t"
#      - "gcr.io/bigquerysheets-404104/dbt-bigquery:latest"
#      - "scotia_project_dbt/"
#
#  - name: "gcr.io/bigquerysheets-404104/dbt-bigquery:latest"
#    entrypoint: 'bash'
#    dir: "scotia_project_dbt"
#    args:
#      - '-c'
#      - |
#        dbt debug

timeout: 1200s

images:
  - "gcr.io/bigquerysheets-404104/dbt-bigquery:latest"

options:
  logging: CLOUD_LOGGING_ONLY
