version: 2

models:
  - name: stg_nvda
    description: "Staging model for NVDA stock data"
    schema: staging
    tests:
      - dbt_expectations.expect_table_row_count_to_equal:
          value: 390
          severity: warn
    columns:
      - name: datetime_est
        description: "Unique datetime"
        tests:
          - not_null:
              config:
                severity: warn
          - unique:
              config:
                severity: warn
      - name: open
        description: "Opening stock price"
        tests:
          - not_null:
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              severity: warn

  - name: ohlc_nvda
    description: "OHLC model for NVDA stock data"
    schema: warehouse
    tests:
      - dbt_expectations.expect_table_row_count_to_equal:
          value: 1
          severity: warn
